### PR TITLE
called fix

### PR DESCRIPTION
**Pull request by retyui**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@retyui we don't have tests here :disappointed: can you check locally what callback fired?

**Comment by retyui** [comment]
@evilebottnawi 
I clone this branch (`"browser-sync-dev-hot-webpack-plugin": "retyui/browser-sync-dev-hot-webpack-plugin#fix-callback",`) to my project. 

Here are the results:
image

**Comment by belvg** [comment]
@evilebottnawi up!

**Comment by evilebottnawi** [comment]
@retyui in near future i release

**Pull request merged**
