### PR TITLE
Fix overwrite middleware if proxy is String

### PR DESCRIPTION
**Pull request by retyui**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@retyui thanks for PR in near future i review this :+1:

**Comment by evilebottnawi** [comment]
@retyui please fix stylistics problem `npm run lint`

**Comment by retyui** [comment]
image
I lost the previous repo, and I do not know how to restore the history of the commits.
You can correct the errors of the linter?

**Comment by evilebottnawi** [comment]
@retyui only late, there are a lot of work, sorry

**Comment by retyui** [comment]
Ok, i create new

**Comment by retyui** [comment]
done https://github.com/itgalaxy/browser-sync-dev-hot-webpack-plugin/pull/30

**Pull request closed without merging**
